# Generated by Django 5.2.9 on 2025-12-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_roommembership_muted_until_roommembership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('chat', 'Chat'), ('join', 'Join'), ('leave', 'Leave'), ('system', 'System')], default='chat', max_length=10),
        ),
    ]
