# Generated by Django 5.2.9 on 2025-12-26 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_message_replied_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together={('user', 'message', 'emoji')},
        ),
        migrations.CreateModel(
            name='PomodoroSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('work', 'Focus'), ('short_break', 'Short Break'), ('long_break', 'Long Break')], default='work', max_length=20)),
                ('is_running', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('remaining_seconds', models.IntegerField(default=1500)),
                ('work_duration', models.IntegerField(default=1500)),
                ('short_break_duration', models.IntegerField(default=300)),
                ('long_break_duration', models.IntegerField(default=900)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pomodoro', to='rooms.room')),
            ],
        ),
    ]
