# Generated by Django 5.2.9 on 2025-12-27 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_roomfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='rooms.roomfile'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('chat', 'Chat'), ('file', 'File'), ('join', 'Join'), ('leave', 'Leave'), ('system', 'System')], default='chat', max_length=10),
        ),
    ]
