# Generated by Django 5.2.9 on 2025-12-29 08:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_message_file_alter_message_message_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ICEServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_type', models.CharField(choices=[('stun', 'STUN'), ('turn', 'TURN'), ('turns', 'TURNS')], max_length=5)),
                ('url', models.CharField(help_text='e.g., stun:stun.l.google.com:19302', max_length=255)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('credential', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher priority servers are used first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ICE Server',
                'verbose_name_plural': 'ICE Servers',
                'ordering': ['-priority', 'server_type'],
            },
        ),
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('call_type', models.CharField(choices=[('audio', 'Audio Only'), ('video', 'Video Call')], default='video', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], default='active', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('max_participants', models.PositiveIntegerField(default=10)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_calls', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_sessions', to='rooms.room')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CallParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_audio_enabled', models.BooleanField(default=True)),
                ('is_video_enabled', models.BooleanField(default=True)),
                ('is_screen_sharing', models.BooleanField(default=False)),
                ('is_connected', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_participations', to=settings.AUTH_USER_MODEL)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='rooms.callsession')),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['room', 'status'], name='rooms_calls_room_id_bfddae_idx'),
        ),
        migrations.AddIndex(
            model_name='callparticipant',
            index=models.Index(fields=['call', 'user'], name='rooms_callp_call_id_956aa6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='callparticipant',
            unique_together={('call', 'user')},
        ),
    ]
